Cookie initialy baked by NetworkToCode Cookie Drift Manager Tool
nautobot/nautobot-plugin-welcome-wizard pull request #82
Opened 2023-10-24 12:01 UTC by snaselj

Template:

```
{
    "template": "https://github.com/nautobot/cookiecutter-nautobot-app.git",
    "dir": "nautobot-app",
    "ref": "develop",
    "path": null
}
```

Cookie:

```
{
    "remote": "https://github.com/nautobot/nautobot-plugin-welcome-wizard.git",
    "path": "/opt/ntc/drift-manager/outputs/nautobot-plugin-welcome-wizard",
    "repository_path": "/opt/ntc/drift-manager/outputs/nautobot-plugin-welcome-wizard",
    "dir": "",
    "branch_prefix": "drift-manager",
    "context": {
        "codeowner_github_usernames": "@smith-ntc",
        "full_name": "Network to Code, LLC",
        "email": "info@networktocode.com",
        "github_org": "nautobot",
        "plugin_name": "welcome_wizard",
        "verbose_name": "Welcome Wizard",
        "plugin_slug": "nautobot-welcome-wizard",
        "project_slug": "nautobot-plugin-welcome-wizard",
        "repo_url": "https://github.com/nautobot/nautobot-plugin-welcome-wizard",
        "base_url": "nautobot-welcome-wizard",
        "min_nautobot_version": "1.5.0",
        "max_nautobot_version": "1.9999",
        "camel_name": "NautobotWelcomeWizard",
        "project_short_description": "Welcome Wizard",
        "model_class_name": "None",
        "open_source_license": "Apache-2.0",
        "docs_base_url": "https://docs.nautobot.com",
        "docs_app_url": "https://docs.nautobot.com/projects/welcome-wizard/en/latest",
        "_template": "https://github.com/nautobot/cookiecutter-nautobot-app.git",
        "_output_dir": "/opt/ntc/drift-manager/outputs",
        "_repo_dir": "/opt/ntc/drift-manager/outputs/.cookiecutters/cookiecutter-nautobot-app/nautobot-app",
        "_checkout": "develop"
    },
    "base_branch": "develop",
    "remote_name": "origin",
    "pull_request_strategy": "PullRequestStrategy.CREATE",
    "post_actions": [
        "PostAction.BLACK"
    ],
    "baked_commit_ref": "",
    "draft": true
}
```

CLI Arguments:

```
{
    "cookie_dir": "",
    "input": false,
    "json_filename": "setup-cookie-welcome-wizard.json",
    "output_dir": "./outputs",
    "push": true,
    "template": "https://github.com/nautobot/cookiecutter-nautobot-app.git",
    "template_dir": "nautobot-app",
    "template_ref": "develop",
    "pull_request": null,
    "post_action": [
        "black"
    ],
    "disable_post_actions": false,
    "draft": true
}
```

2023-10-24 14:10 UTC, snaselj commented
Ready for review now.

cc.: @whitej6

2023-10-24 14:20 UTC, whitej6 requested changes

2023-10-24 14:20 UTC, whitej6 commented on docs/dev/arch_decision.md
> +!!! warning "Developer Note - Remove Me!"
fill in or remove

2023-10-24 14:20 UTC, whitej6 commented on docs/user/external_interactions.md
> +## External System Integrations
fill in or remove

2023-11-10 16:24 UTC, jvanderaa requested changes

2023-11-10 16:24 UTC, jvanderaa commented on .github/ISSUE_TEMPLATE/bug_report.md
> +* Nautobot version:  <!-- Example: 1.6.0 -->
Not really necessary to update.

2023-11-10 16:24 UTC, jvanderaa commented on .flake8
> +  W503   # Black disagrees with this rule, as does PEP 8; Black wins
What is this changing? Doesn't seem to have a functional change.

2023-11-10 16:24 UTC, jvanderaa commented on .gitignore
> -docs/CHANGELOG.md
Why are we removing these?

2023-11-10 16:24 UTC, jvanderaa commented on development/docker-compose.base.yml
> +      - *nautobot-build
```suggestion
    <<: =[*nautobot-base, *nautobot-build]
```
Suggestion to follow what has come before.

2023-11-10 16:27 UTC, jvanderaa requested changes

2023-11-10 16:27 UTC, jvanderaa commented on development/development.env
> -NAUTOBOT_DJANGO_TOOLBAR_ENABLED=True
What is with removing these?

2023-11-10 16:27 UTC, jvanderaa commented on development/docker-compose.dev.yml
> +      test: ["CMD", "true"]  # Due to layering, disable: true won't work. Instead, change the test
Remove.

2023-11-10 16:27 UTC, jvanderaa commented on development/docker-compose.dev.yml
> +      test: ["CMD", "true"]  # Due to layering, disable: true won't work. Instead, change the test
Remove.

2023-11-10 16:37 UTC, jvanderaa approved these changes

2023-11-10 16:39 UTC, whitej6 approved these changes

2023-11-10 16:39 UTC, merged